[package]
name = "rusty-json"
version = "0.1.0"
authors = ["Andrew O'Doherty <andrew.odoherty@daimler.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
